import { Vehicle, Trip, FuelLog, MaintenanceItem, SavedLocation, UserSettings } from '../types';

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh_honda_city',
    name: 'Honda City',
    make: 'Honda',
    model: 'City 1.5 Aspire',
    year: 2022,
    fuelType: 'petrol',
    odometerKm: 152430,
    licensePlate: 'BC-8492',
    isDefault: true,
    fuelCapacityL: 40,
    tankLevelPercent: 68,
    color: '#1E3A8A',
  },
  {
    id: 'veh_toyota_corolla',
    name: 'Toyota Corolla',
    make: 'Toyota',
    model: 'Corolla Altis 1.6',
    year: 2020,
    fuelType: 'petrol',
    odometerKm: 89400,
    licensePlate: 'LE-4102',
    isDefault: false,
    fuelCapacityL: 50,
    tankLevelPercent: 45,
    color: '#0D9488',
  },
];

const now = Date.now();
const oneDayMs = 24 * 60 * 60 * 1000;

// Pre-generated realistic coordinate path between Home and Office
export const SAMPLE_ROUTE_HOME_TO_OFFICE = [
  { lat: 24.9180, lng: 67.0971, timestamp: now - 38 * 60 * 1000, speedKmh: 0, heading: 210 },
  { lat: 24.9142, lng: 67.0920, timestamp: now - 35 * 60 * 1000, speedKmh: 42, heading: 220 },
  { lat: 24.9050, lng: 67.0810, timestamp: now - 30 * 60 * 1000, speedKmh: 58, heading: 235 },
  { lat: 24.8920, lng: 67.0650, timestamp: now - 24 * 60 * 1000, speedKmh: 68, heading: 240 },
  { lat: 24.8780, lng: 67.0450, timestamp: now - 18 * 60 * 1000, speedKmh: 74, heading: 230 },
  { lat: 24.8650, lng: 67.0280, timestamp: now - 11 * 60 * 1000, speedKmh: 52, heading: 225 },
  { lat: 24.8580, lng: 67.0180, timestamp: now - 6 * 60 * 1000, speedKmh: 35, heading: 215 },
  { lat: 24.8532, lng: 67.0099, timestamp: now - 1 * 60 * 1000, speedKmh: 0, heading: 210 },
];

export const INITIAL_TRIPS: Trip[] = [
  {
    id: 'trip_1',
    vehicleId: 'veh_honda_city',
    startTime: now - (2 * 3600 * 1000 + 40 * 60 * 1000),
    endTime: now - (2 * 3600 * 1000 + 2 * 60 * 1000),
    distanceKm: 18.7,
    durationSeconds: 38 * 60,
    movingTimeSeconds: 32 * 60,
    stoppedTimeSeconds: 6 * 60,
    avgSpeedKmh: 35.1,
    maxSpeedKmh: 76.5,
    startLocationName: 'Home',
    endLocationName: 'Office',
    category: 'Commute',
    notes: 'Morning office drive. Light traffic on Expressway.',
    points: SAMPLE_ROUTE_HOME_TO_OFFICE,
  },
  {
    id: 'trip_2',
    vehicleId: 'veh_honda_city',
    startTime: now - (8 * 3600 * 1000 + 45 * 60 * 1000),
    endTime: now - (8 * 3600 * 1000 + 4 * 60 * 1000),
    distanceKm: 19.2,
    durationSeconds: 41 * 60,
    movingTimeSeconds: 34 * 60,
    stoppedTimeSeconds: 7 * 60,
    avgSpeedKmh: 33.8,
    maxSpeedKmh: 71.0,
    startLocationName: 'Office',
    endLocationName: 'Home',
    category: 'Commute',
    notes: 'Evening return commute.',
    points: [...SAMPLE_ROUTE_HOME_TO_OFFICE].reverse(),
  },
  {
    id: 'trip_3',
    vehicleId: 'veh_honda_city',
    startTime: now - (14 * 3600 * 1000),
    endTime: now - (13 * 3600 * 1000 + 46 * 60 * 1000),
    distanceKm: 38.5,
    durationSeconds: 56 * 60,
    movingTimeSeconds: 48 * 60,
    stoppedTimeSeconds: 8 * 60,
    avgSpeedKmh: 48.1,
    maxSpeedKmh: 88.0,
    startLocationName: 'Home',
    endLocationName: 'Airport Terminal 1',
    category: 'Business',
    notes: 'Client pickup from airport.',
    points: SAMPLE_ROUTE_HOME_TO_OFFICE,
  },
  {
    id: 'trip_4',
    vehicleId: 'veh_honda_city',
    startTime: now - (oneDayMs + 3600 * 1000 * 3),
    endTime: now - (oneDayMs + 3600 * 1000 * 1.5),
    distanceKm: 82.7,
    durationSeconds: 102 * 60,
    movingTimeSeconds: 88 * 60,
    stoppedTimeSeconds: 14 * 60,
    avgSpeedKmh: 56.4,
    maxSpeedKmh: 91.2,
    startLocationName: 'Home',
    endLocationName: 'Highway Hub & Resort',
    category: 'Road Trip',
    notes: 'Weekend highway drive. Engine performed smoothly.',
    points: SAMPLE_ROUTE_HOME_TO_OFFICE,
  },
  {
    id: 'trip_5',
    vehicleId: 'veh_honda_city',
    startTime: now - (oneDayMs * 3),
    endTime: now - (oneDayMs * 3 - 35 * 60 * 1000),
    distanceKm: 14.2,
    durationSeconds: 28 * 60,
    movingTimeSeconds: 24 * 60,
    stoppedTimeSeconds: 4 * 60,
    avgSpeedKmh: 35.5,
    maxSpeedKmh: 64.0,
    startLocationName: 'Home',
    endLocationName: 'City Mall & Market',
    category: 'Errand',
    notes: 'Weekly grocery run.',
    points: SAMPLE_ROUTE_HOME_TO_OFFICE,
  },
];

export const INITIAL_FUEL_LOGS: FuelLog[] = [
  {
    id: 'fuel_1',
    vehicleId: 'veh_honda_city',
    date: new Date(now - oneDayMs * 2).toISOString().split('T')[0],
    quantityL: 12.0,
    pricePerUnit: 322,
    totalAmount: 3864,
    odometerKm: 152430,
    fuelStation: 'Shell Expressway',
    fullTank: false,
    notes: 'Quick top-up before weekly commuting.',
  },
  {
    id: 'fuel_2',
    vehicleId: 'veh_honda_city',
    date: new Date(now - oneDayMs * 9).toISOString().split('T')[0],
    quantityL: 34.5,
    pricePerUnit: 320,
    totalAmount: 11040,
    odometerKm: 151980,
    fuelStation: 'Total Parco',
    fullTank: true,
    notes: 'Full tank fill. Excellent mileage observed.',
  },
  {
    id: 'fuel_3',
    vehicleId: 'veh_honda_city',
    date: new Date(now - oneDayMs * 18).toISOString().split('T')[0],
    quantityL: 38.0,
    pricePerUnit: 318,
    totalAmount: 12084,
    odometerKm: 151420,
    fuelStation: 'PSO City Station',
    fullTank: true,
  },
];

export const INITIAL_MAINTENANCE: MaintenanceItem[] = [
  {
    id: 'maint_oil',
    vehicleId: 'veh_honda_city',
    title: 'Engine Oil & Filter',
    category: 'oil',
    lastServiceKm: 152000,
    nextServiceKm: 157000,
    lastServiceDate: '2026-08-15',
    notes: '5W-30 Synthetic oil with genuine Honda oil filter.',
    estimatedCost: 8500,
  },
  {
    id: 'maint_brakes',
    vehicleId: 'veh_honda_city',
    title: 'Brake Service & Pads',
    category: 'brakes',
    lastServiceKm: 145000,
    nextServiceKm: 155000,
    lastServiceDate: '2026-05-10',
    notes: 'Front brake pads inspected at 60% life.',
    estimatedCost: 6500,
  },
  {
    id: 'maint_tyres',
    vehicleId: 'veh_honda_city',
    title: 'Tyre Rotation & Alignment',
    category: 'tyres',
    lastServiceKm: 148000,
    nextServiceKm: 158000,
    lastServiceDate: '2026-06-20',
    notes: 'All 4 tyres balanced and rotated.',
    estimatedCost: 3000,
  },
  {
    id: 'maint_battery',
    vehicleId: 'veh_honda_city',
    title: 'Battery Health Inspection',
    category: 'battery',
    lastServiceKm: 140000,
    nextServiceKm: 155000,
    lastServiceDate: '2026-03-12',
    notes: 'Voltage steady at 12.6V resting, terminals cleaned.',
    estimatedCost: 1500,
  },
  {
    id: 'maint_filter',
    vehicleId: 'veh_honda_city',
    title: 'Engine Air Filter & Cabin Filter',
    category: 'filter',
    lastServiceKm: 150000,
    nextServiceKm: 160000,
    lastServiceDate: '2026-07-04',
    notes: 'Replaced OEM air intake filter.',
    estimatedCost: 4200,
  },
  {
    id: 'maint_ac',
    vehicleId: 'veh_honda_city',
    title: 'AC Service & Refrigerant Check',
    category: 'ac',
    lastServiceKm: 135000,
    nextServiceKm: 155000,
    lastServiceDate: '2026-02-18',
    notes: 'Cooling gas pressure optimal.',
    estimatedCost: 5500,
  },
];

export const INITIAL_SAVED_LOCATIONS: SavedLocation[] = [
  {
    id: 'loc_home',
    name: 'Home',
    category: 'home',
    lat: 24.9180,
    lng: 67.0971,
    address: 'Gulshan Block 4, Main Boulevard',
  },
  {
    id: 'loc_office',
    name: 'Office',
    category: 'work',
    lat: 24.8532,
    lng: 67.0099,
    address: 'I.I. Chundrigar Road, Financial Tower',
  },
  {
    id: 'loc_gym',
    name: 'Gym',
    category: 'gym',
    lat: 24.9205,
    lng: 67.0900,
    address: 'FitPro Fitness Club',
  },
  {
    id: 'loc_uni',
    name: 'University',
    category: 'education',
    lat: 24.9312,
    lng: 67.1121,
    address: 'University Campus, Main Gate',
  },
  {
    id: 'loc_family',
    name: 'Family Home',
    category: 'family',
    lat: 24.8710,
    lng: 67.0600,
    address: 'Defence Phase 5, Karachi',
  },
];

export const INITIAL_SETTINGS: UserSettings = {
  theme: 'system',
  unitDistance: 'km',
  unitFuel: 'L',
  currency: 'Rs.',
  safetyMode: true,
  highAccuracyGps: true,
  completedOnboarding: true,
  hasAskedLocationPermission: false,
};
